### ISSUE TITLE
Manque répertoire Model\Base

### ISSUE THREAD

**Issue by TheCoreDev31** [thelia-modules/ColissimoWs#2]
Le fichier ColissimoWs.php fait appel à une classe ColissimoWs\Model\Base\ColissimowsLabelQuery qui n'existe pas (il n'y a pas de sous-dossier Base dans le répertoire Model)

Conséquence immédiate : impossible d'activer le module.
Et même après activation manuelle, plantage PHP dans le back-office suite à erreur dans le HookManager.php, lors de l'appel à la méthode Create du ColissimowsLabelQuery

**Comment by lopes-vincent** [comment]
Bonjour, 
Sur quelle version de Thelia êtes vous ?

**Comment by TheCoreDev31** [comment]
Bonjour,


J’ai testé sur une version 2.3.4 « clean Install ».
Et j’ai le même comportement sur une Thelia 2.3.4 customisée pour mon client.


Le 6 mai 2020 à 10:30:43, Vincent Lopes-Vicente (notifications@github.com) a écrit:

Bonjour,
Sur quelle version de Thelia êtes vous ?

**Comment by lopes-vincent** [comment]
Il y a effectivement un problème qui rend le module incompatible avec les Thelia < 2.4.0.
Nous sommes en train de travailler sur une nouvelle version de ce module qui corrigera ce probléme.
En attendant pour faire fonctionner ce module sur un Thelia 2.3.4 vous pouvez éxecuter cette command qui regénéreras les models `php Thelia module:generate:model ColissimoWs`

**Comment by TheCoreDev31** [comment]
Bonjour,

Merci de votre aide.
Il y a en effet du mieux sur mon Thelia 2.3.4 standard, mais sur la boutique de mon client (avec tous les autres modules désactivés), j’obtiens une erreur 500 dans le return de $response (ligne 46 de SoapClientWithAttachements.php)
Un problème avec la classe Message du package-colissimo-postage apparement :-(


Le 6 mai 2020 à 11:03:18, Vincent Lopes-Vicente (notifications@github.com) a écrit:

Il y a effectivement un problème qui rend le module incompatible avec les Thelia < 2.4.0.
Nous sommes en train de travailler sur une nouvelle version de ce module qui corrigera ce probléme.
En attendant pour faire fonctionner ce module sur un Thelia 2.3.4 vous pouvez éxecuter cette command qui regénéreras les models php Thelia module:generate:model ColissimoWs

**Comment by TheCoreDev31** [comment]
Re-bonjour,


Ne tenez pas compte de mon précédent message : en utilisant la v1 du WebService (et pas le WDSL 2.0), j’arrive bien à mes fins.
Merci encore de votre aide.


Le 6 mai 2020 à 11:03:18, Vincent Lopes-Vicente (notifications@github.com) a écrit:

Il y a effectivement un problème qui rend le module incompatible avec les Thelia < 2.4.0.
Nous sommes en train de travailler sur une nouvelle version de ce module qui corrigera ce probléme.
En attendant pour faire fonctionner ce module sur un Thelia 2.3.4 vous pouvez éxecuter cette command qui regénéreras les models php Thelia module:generate:model ColissimoWs

**Comment by lopes-vincent** [comment]
Merci pour votre retour.

**Comment by TheCoreDev31** [comment]
Juste 2 suggestions pour conclure : 
- indiquer le contournement possible, quelque part sur GitHub
- si confirmé, préciser dans le ReadMe le endpoint à utiliser


Le 7 mai 2020 à 12:18:29, Vincent Lopes-Vicente (notifications@github.com) a écrit:

Merci pour votre retour.
